name: PyRAT
ami: ami-0892d3c7ee96c0bf7
scripts_dir: .
manual_installation_step: False
run_installation_script_as_root: False
run_post_installation_script_as_root: False
run_toolkit_as_root: False
description: Abstract Interpretation based analysis tool
